


<div class="container">
<div class="center">
  
<form class="form-control" id="enviodados" action="/registrar" method="post"> 
    <div class="divErro" id="erros"></div>
     <div class="clearStorage" id="clear"> <button class="btn btn- nav-easy nav-color" id="clearStorage">Limpar Formulario </button> </div>
 
    <div class="mb-3">
    <label for="InputName" class="form-label">Nome:</label>
    <input type="type" class="form-control" value="<?= $this->view->usuario['InputName']?>"  id="InputName" name="InputName" >
  
   </div>
   <div class="mb-3">
    <label for="InputEmail" class="form-label">Email:</label>
    <input type="email" class="form-control" value="<?= $this->view->usuario['InputEmail']?>" id="InputEmail" name="InputEmail">
     <div class="divErro" id="erroEmail"></div>
    </div>
   <div class="mb-3">
    <label for="InputTel" class="form-label">Telefone</label>
    <input type="tel" class="form-control" id="InputTel" value="<?= $this->view->usuario['InputTel']?>" name="InputTel" maxlength="15" placeholder="(99) 99999-9999">
    <div class="divErro" id="erroTel"></div>
  </div>
  <div class="mb-3">
    <label for="InputDate" class="form-label">Data Nacimento:</label>
    <input type="date" class="form-control" value="<?= $this->view->usuario['InputDate']?>" name="InputDate" id="InputDate">
  </div>
   <?php 
     //apresento mensagem de erro em tela ao usuário
      if(isset($_SESSION['msg'])) {
           echo $_SESSION['msg'];
            header("Refresh:15 url=/");
           unset($_SESSION['msg']);
      }
   ?>

  <input type="submit" value="Salvar" name="acao" class="btn btn-primary nav-easy"/>
</form>
</div>
</div> <!--fechamendo do container-->
<!-- funcionana somente neste página -->
<script type="module" src="js/WebApi/newDados.js"></script>
