



 
?>
<script type="module" src="js/WebApi/newListas.js"></script>
<div id="resultado"></div>
<div class="container">
<div class="center">
<table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        
<?php
        foreach($this->view->dados as $key => $dados){
  
   echo '<th scope="row">1</th>';
   echo "<td>{$dados[0]}</td>";
   echo "<td>{$dados[1]}</td>";
   echo "<td>@mdo</td>";
   echo "</tr>";

 }?>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

</div>
</div>

